name: Check CLI

on:
  push:
    branches: [ update-tfc-backend ]
  workflow_dispatch:

jobs:
  check-cli:
    name: "Check GH CLI"
    env:
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      repo_token: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    #- name: Check gh cli
    #  run: |
    #    echo $repo_token > my-token.txt
    #    gh auth login --with-token < my-token.txt
    #    gh api -H 'Accept: application/vnd.github.v3.raw+json' https://api.github.com/repos/arimaverick/githubactions-demo/dispatches -f body='Hi from CLI'
    - name: Rest API dispatcher-trap
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $repo_token" https://api.github.com/repos/arimaverick/githubactions-demo/dispatches -d '{"event_type":"build", "client_payload": { "version": "1.1.3", "ref": "main"}}'