name: Check CLI

on:
  push:
    branches: [ update-tfc-backend ]
  workflow_dispatch:

jobs:
  check-cli:
    name: "Check GH CLI"
    env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Check gh cli
      run: |
        echo $repo_token > my-token.txt
        gh auth login --with-token < my-token.txt
        rm my-token.txt
